http:
  port: 3100
admin:
  port: 4100
  host: localhost
apiEndpoints:
  userapi:
    host: '*'
    paths: /user/*
serviceEndpoints:
  userservice:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  default:
    apiEndpoints:
      - userapi
    policies:
      - jwt:
          - action:
              secretOrPublicKey: "91249681-5226-4a78-84ee-acfe0d010719"
      - proxy:
          - action:
              serviceEndpoint: userservice 
              changeOrigin: true
