http:
  port: 3100
admin:
  port: 4100
  host: localhost
apiEndpoints:
  api:
    host: localhost
serviceEndpoints:
  userservice:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userservice 
              changeOrigin: true
